#!/bin/bash
# update-meta.sh — Update wiki/index.md and append to wiki/log.md.
#
# Usage: bash update-meta.sh [--rebuild-index]

set -euo pipefail

KIWI_API="${KIWI_API:-http://localhost:3333}"
SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Source path helpers
SOURCE_DIR="wiki/sources"
ENTITY_DIR="wiki/entities"
CONCEPT_DIR="wiki/concepts"

build_index() {
  local index="# Knowledge Wiki Index\n\n"
  index+="Auto-generated by wiki-compilation skill.\n\n"

  # List sources
  index+="## Sources\n\n"
  TREE=$(curl -sf "${KIWI_API}/api/kiwi/tree?path=${SOURCE_DIR}/" 2>/dev/null || echo '[]')
  FILES=$(echo "$TREE" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    if isinstance(data, list):
        for item in data:
            p = item.get('path', item) if isinstance(item, dict) else item
            print(p)
    elif isinstance(data, dict):
        for item in data.get('results', []):
            print(item.get('path', ''))
except: pass
" 2>/dev/null)

  if [ -n "$FILES" ]; then
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      NAME=$(basename "$f" .md)
      TITLE=$(curl -sf "${KIWI_API}/api/kiwi/file?path=${f}" 2>/dev/null \
        | grep "^title:" | sed 's/.*title: *//' | head -1 || echo "$NAME")
      index+="- [[${NAME}|${TITLE}]]\n"
    done <<< "$FILES"
  else
    index+="_(none yet)_\n"
  fi

  # List entities
  index+="\n## Entities\n\n"
  TREE=$(curl -sf "${KIWI_API}/api/kiwi/tree?path=${ENTITY_DIR}/" 2>/dev/null || echo '[]')
  FILES=$(echo "$TREE" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    if isinstance(data, list):
        for item in data:
            p = item.get('path', item) if isinstance(item, dict) else item
            print(p)
    elif isinstance(data, dict):
        for item in data.get('results', []):
            print(item.get('path', ''))
except: pass
" 2>/dev/null)
  if [ -n "$FILES" ]; then
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      NAME=$(basename "$f" .md)
      index+="- [[${NAME}]]\n"
    done <<< "$FILES"
  else
    index+="_(none yet)_\n"
  fi

  # List concepts
  index+="\n## Concepts\n\n"
  TREE=$(curl -sf "${KIWI_API}/api/kiwi/tree?path=${CONCEPT_DIR}/" 2>/dev/null || echo '[]')
  FILES=$(echo "$TREE" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    if isinstance(data, list):
        for item in data:
            p = item.get('path', item) if isinstance(item, dict) else item
            print(p)
    elif isinstance(data, dict):
        for item in data.get('results', []):
            print(item.get('path', ''))
except: pass
" 2>/dev/null)
  if [ -n "$FILES" ]; then
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      NAME=$(basename "$f" .md)
      index+="- [[${NAME}]]\n"
    done <<< "$FILES"
  else
    index+="_(none yet)_\n"
  fi

  printf '%b' "$index"
}

append_log() {
  local entry="$1"
  curl -s -X POST "${KIWI_API}/api/kiwi/file/append?path=wiki/log.md" \
    -H "X-Actor: agent:mercury" \
    --data-binary "$entry" > /dev/null
  echo "LOG: appended entry"
}

case "${1:-}" in
  --rebuild-index)
    INDEX=$(build_index)
    bash "$SKILL_DIR/references/write-page.sh" "wiki/index.md" "$INDEX"
    ;;
  --log)
    shift
    append_log "$*"
    ;;
  *)
    echo "Usage: update-meta.sh --rebuild-index | --log <entry>" >&2
    exit 1
    ;;
esac
